/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Locality;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.ClinicOrganization;
import Model.RoundedBorder;
import Model.UserDetails.UserDetails;
import Model.WorkQueue.LocalityFireRequest;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Sand
 */
public class LocalityAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LocalityAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    UserDetails userAccount;
   

    public LocalityAdminWorkAreaJPanel(JPanel userProcessContainer , UserDetails userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        
        
//        btnDonateBlood.setBorder(new RoundedBorder(20));
//        btnPoliceService.setBorder(new RoundedBorder(20));
//        btnRequestBlood.setBorder(new RoundedBorder(20));
//        btnRequestHospital1.setBorder(new RoundedBorder(20));
//        btnRequestHelpingHands.setBorder(new RoundedBorder(20));
//        jButton1.setBorder(new RoundedBorder(20));
//        jToggleButton1.setBorder(new RoundedBorder(20));
//        btnRequestHospital.setBorder(new RoundedBorder(20));
        

        //enterpriseNameLabel.setText(enterprise.getName()); //erated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

//    public LocalityAdminWorkAreaJPanel(JPanel UserContainer, UserDetails userAccount, ClinicOrganization clinicOrganization, Enterprise enterprise, EcoSystem system) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestHelpingHands = new javax.swing.JButton();
        btnRequestHospital = new javax.swing.JButton();
        btnDonateBlood = new javax.swing.JButton();
        btnRequestBlood = new javax.swing.JButton();
        btnRequestShelter = new javax.swing.JButton();
        btnRequestHealthAid = new javax.swing.JButton();
        btnPoliceService = new javax.swing.JButton();
        btnFireRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SPTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelArea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequestHelpingHands.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestHelpingHands.setText("Request Food");
        btnRequestHelpingHands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHelpingHandsActionPerformed(evt);
            }
        });
        add(btnRequestHelpingHands, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, 30));

        btnRequestHospital.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestHospital.setText("Request Community Health Aid");
        btnRequestHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHospitalActionPerformed(evt);
            }
        });
        add(btnRequestHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 250, -1));

        btnDonateBlood.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDonateBlood.setText("Donate Blood");
        btnDonateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateBloodActionPerformed(evt);
            }
        });
        add(btnDonateBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 250, -1));

        btnRequestBlood.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestBlood.setText("Request Blood");
        btnRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBloodActionPerformed(evt);
            }
        });
        add(btnRequestBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 250, -1));

        btnRequestShelter.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestShelter.setText("Request Shelter");
        btnRequestShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestShelterActionPerformed(evt);
            }
        });
        add(btnRequestShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 250, -1));

        btnRequestHealthAid.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRequestHealthAid.setText("Request Patient Health Aid");
        btnRequestHealthAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHealthAidActionPerformed(evt);
            }
        });
        add(btnRequestHealthAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 250, -1));

        btnPoliceService.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPoliceService.setText("Request Police Service");
        btnPoliceService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceServiceActionPerformed(evt);
            }
        });
        add(btnPoliceService, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 250, -1));

        btnFireRequest.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnFireRequest.setText("Fire Request");
        btnFireRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFireRequestActionPerformed(evt);
            }
        });
        add(btnFireRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 520, 470));

        SPTitle.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        SPTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SPTitle.setText("Community Panel");
        add(SPTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_website_-_male_user_3440844 (1).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location 32x.png"))); // NOI18N
        labelArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelAreaMousePressed(evt);
            }
        });
        add(labelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestHelpingHandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHelpingHandsActionPerformed
        // TODO add your handling code here:
        try{
        RequestHelpingHandsJPanel requestHelpingHandsJPanel = new RequestHelpingHandsJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestHelpingHandsJPanel",requestHelpingHandsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRequestHelpingHandsActionPerformed

    private void btnRequestHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHospitalActionPerformed
        // TODO add your handling code here:
        try{
        RequestHospitalJPanel requestHospitalJPanel = new RequestHospitalJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestHospitalJPanel",requestHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRequestHospitalActionPerformed

    private void btnDonateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateBloodActionPerformed
        // TODO add your handling code here:
        try{
        RequestDonateBloodJPanel requestDonateBloodJPanel = new RequestDonateBloodJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestDonateBloodJPanel",requestDonateBloodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDonateBloodActionPerformed

    private void btnRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBloodActionPerformed
        // TODO add your handling code here:
        try{
        RequestBloodFromBankJPanel requestBloodFromBank = new RequestBloodFromBankJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestBloodFromBank",requestBloodFromBank);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRequestBloodActionPerformed

    private void btnRequestShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestShelterActionPerformed
        // TODO add your handling code here:
        try{
        RequestShelterJPanel requestShelterJPanel = new RequestShelterJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("RequestShelterJPanel",requestShelterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRequestShelterActionPerformed

    private void btnRequestHealthAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHealthAidActionPerformed
        // TODO add your handling code here:
        try{
        RequestMedicLocalityAreaJPanel requestMedicLocalityAreaJPanel = new RequestMedicLocalityAreaJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("RequestMedicLocalityAreaJPanel",requestMedicLocalityAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRequestHealthAidActionPerformed

    private void btnPoliceServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceServiceActionPerformed
        // TODO add your handling code here:
        try{
        RequestPoliceJPanel requestPoliceJPanel = new RequestPoliceJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
        userProcessContainer.add("requestPoliceJPanel",requestPoliceJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
      
    }//GEN-LAST:event_btnPoliceServiceActionPerformed

    private void btnFireRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFireRequestActionPerformed
        // TODO add your handling code here:
        try{
          RequestIncidentDepartmentJPanel requestIncidentDepartmentJPanel = new  RequestIncidentDepartmentJPanel(userProcessContainer, userAccount, enterprise, ecoSystem);
         userProcessContainer.add("requestIncidentDepartmentJPanel",requestIncidentDepartmentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFireRequestActionPerformed

    private void labelAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAreaMousePressed
        // TODO add your handling code here:
        try{
        LocalitySetUpInformation communitySetUpInformation = new LocalitySetUpInformation(userProcessContainer, enterprise.getOrganizationDirectory(), enterprise, ecoSystem, userAccount);
        userProcessContainer.add("LocalitySetUpInformation", communitySetUpInformation);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        catch(NullPointerException e){
             JOptionPane.showMessageDialog(null, "Some error occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_labelAreaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SPTitle;
    private javax.swing.JButton btnDonateBlood;
    private javax.swing.JButton btnFireRequest;
    private javax.swing.JButton btnPoliceService;
    private javax.swing.JButton btnRequestBlood;
    private javax.swing.JButton btnRequestHealthAid;
    private javax.swing.JButton btnRequestHelpingHands;
    private javax.swing.JButton btnRequestHospital;
    private javax.swing.JButton btnRequestShelter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelArea;
    // End of variables declaration//GEN-END:variables
}
