/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Locality;

import Model.MealandShelterDistributor.Meal;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.ClinicOrganization;
import Model.UserDetails.UserDetails;
import Model.Utils.HeaderColors;
import Model.WorkQueue.LocalityMealRequest;
import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class RequestHelpingHandsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestHelpingHandsJPanel
     * 
     */
     private JPanel userProcessContainer;
//    private ClinicOrganization organization;
    private Enterprise enterprise;
    private UserDetails account;
    private EcoSystem ecoSystem;
//    public RequestHelpingHandsJPanel() {
//        initComponents();
//        
//    }

    public RequestHelpingHandsJPanel(JPanel userProcessContainer, UserDetails account, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.ecoSystem = ecoSystem;
        tblRequest.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateMealTypeComboBox();
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtPurpose = new javax.swing.JTextField();
        btnSendRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        foodTypeComboBox = new javax.swing.JComboBox<>();
        txtVenue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeopleCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 24)); // NOI18N
        jLabel1.setText("Request For Meal Assistance");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 360, -1));

        btnBack.setBackground(new java.awt.Color(102, 217, 255));
        btnBack.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        txtPurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurposeActionPerformed(evt);
            }
        });
        add(txtPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 140, -1));

        btnSendRequest.setBackground(new java.awt.Color(102, 217, 255));
        btnSendRequest.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        add(btnSendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        tblRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRequest.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meal Type", "No of People Affected", "Venue", "No of Packets", "Status", "Requested Date", "Resolution Date", "Sender", "Receiver"
            }
        ));
        tblRequest.setGridColor(new java.awt.Color(0, 0, 0));
        tblRequest.setShowGrid(true);
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 600, 176));

        jLabel7.setText("#People req :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        foodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(foodTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 138, -1));
        add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        jLabel2.setText("Meal Type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));
        add(txtPeopleCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 140, -1));

        jLabel5.setText("Area :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel3.setText("#Meal Packets : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IndividualOpaque.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 670, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Meal1.jpeg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurposeActionPerformed

    
     private void populateMealTypeComboBox(){
        DefaultComboBoxModel modelMedicType = new DefaultComboBoxModel();
        for (Meal food : ecoSystem.getMealDirectory().getMealList() ) {
            modelMedicType.addElement(food.getMealType());
        }
        
        foodTypeComboBox.setModel(modelMedicType);
    }
    
    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        
        if(txtPeopleCount.getText().isEmpty() || txtPurpose.getText().isEmpty() || txtVenue.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Please add all the fields");
        return;
        }
        
        LocalityMealRequest request =  new LocalityMealRequest();
        Date date = new Date();
        request.setRequestDate(date);
        request.setArea(txtVenue.getText());
        
        try{
                request.setNoPeopleRequestingMeal(Integer.parseInt(txtPeopleCount.getText()));
                request.setNoOfPackets(Integer.parseInt(txtPurpose.getText()));

        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Please enter numeric values");
        return;
        }
        
        request.setStatus("Requested");
        request.setSender(account);
        
        try{
            request.setRequestedMealType(foodTypeComboBox.getSelectedItem().toString());

        }catch(NullPointerException n){
         JOptionPane.showMessageDialog(this, "Please wait for an update");
        return;
        }
        
        account.getWorkQueue().getWorkRequestList().add(request);
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        ecoSystem.getWorkQueue().getWorkRequestList().add(request);
        populateRequestTable();
    }//GEN-LAST:event_btnSendRequestActionPerformed

    
    private void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        for(WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
            if(work instanceof LocalityMealRequest && work.getSender() == account){
                Object[] row = new Object[9];
                row[0] = ((LocalityMealRequest) work).getRequestedMealType() ;
                row[3] = ((LocalityMealRequest) work).getRequestDate() ;
                row[1] = ((LocalityMealRequest) work).getNoPeopleRequestingMeal() ;
                row[2] = ((LocalityMealRequest) work).getArea() ;
                row[6] = work;
                row[5] = ((LocalityMealRequest) work).getNoOfPackets() ;
                row[4] = ((LocalityMealRequest) work).getResolveDate();
                row[7] = ((LocalityMealRequest) work).getSender().getNameuser();
                
                if(((LocalityMealRequest) work).getReceiver() != null){
                row[8] = ((LocalityMealRequest) work).getReceiver().getNameuser();
                }
                
                
                model.addRow(row);
            
            }
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> foodTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtPeopleCount;
    private javax.swing.JTextField txtPurpose;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
