/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HelpingHands.Meal;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.MealOrganization;
import Model.Organization.Organization;
import Model.RoundedBorder;
import Model.UserDetails.UserDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ShubhamSingh
 */
public class MealAdminWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MealAdminWAJPanel
     */
    JPanel userProcessContainer;
    UserDetails userAccount;
    MealOrganization foodOrganization;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    public MealAdminWAJPanel(JPanel userProcessContainer,
    UserDetails userAccount,
    MealOrganization foodOrganization,
    Enterprise enterprise,
    EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.foodOrganization = foodOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        
        jMngInvBtn.setBorder(new RoundedBorder(20));
        jMealReqBtn.setBorder(new RoundedBorder(20));
        //jShelterReqBtn.setBorder(new RoundedBorder(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMngInvBtn = new javax.swing.JButton();
        jMealReqBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jMngInvBtn.setBackground(new java.awt.Color(255, 146, 146));
        jMngInvBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jMngInvBtn.setForeground(new java.awt.Color(255, 255, 255));
        jMngInvBtn.setText("Manage Inventory");
        jMngInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMngInvBtnActionPerformed(evt);
            }
        });

        jMealReqBtn.setBackground(new java.awt.Color(255, 146, 146));
        jMealReqBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jMealReqBtn.setForeground(new java.awt.Color(255, 255, 255));
        jMealReqBtn.setText("Locality Food Requests");
        jMealReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMealReqBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setText("Meal Service");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fs1.jpeg"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/March_Meal-Prep.jpeg"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jMngInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386)
                        .addComponent(jMealReqBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel1)))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMngInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMealReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMealReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMealReqBtnActionPerformed
        // TODO add your handling code here:
        ManageLocalityMealRequestJPanel communityMealRequestJPanel = new ManageLocalityMealRequestJPanel(userProcessContainer,enterprise.getOrganizationDirectory(), enterprise, ecoSystem,userAccount);
        userProcessContainer.add("communityMealRequestJPanel", communityMealRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jMealReqBtnActionPerformed

    private void jMngInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMngInvBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(!ecoSystem.getMealDirectory().getMealList().isEmpty()){
                ManageMealInventory manageMealInventory = new ManageMealInventory(userProcessContainer, enterprise, ecoSystem, userAccount,enterprise.getOrganizationDirectory());
                userProcessContainer.add("ManageMealInventory", manageMealInventory);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                JOptionPane.showMessageDialog(null, "No Meal Packet!! Please login with FS Distributor and create food!!", "Warning", JOptionPane.WARNING_MESSAGE);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Some Error Occurred!!", "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jMngInvBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jMealReqBtn;
    private javax.swing.JButton jMngInvBtn;
    // End of variables declaration//GEN-END:variables
}
