/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Medic;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.Organization.OrganizationDirectory;
import Model.UserDetails.UserDetails;
import Model.Utils.HeaderColors;
import Model.Utils.Validation;
import Model.WorkQueue.LocalityMedicRequest;
import Model.WorkQueue.PatientMedicRequest;
import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ShubhamSingh
 */
public class MedicWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserDetails userAccount;
    Organization organization;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    private Validation validation;


    public MedicWorkAreaJPanel(JPanel UserContainer, UserDetails userAccount, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = UserContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.ecoSystem = system;
        this.enterprise = enterprise;
        this.validation = new Validation();
        tblRequestTablePatient.getTableHeader().setDefaultRenderer(new HeaderColors());
        
        //System.out.println("ui.Medic.MedicWorkAreaJPanel.<init>()"+userAccount.getUsername());
        
        lblMedicName.setText(userAccount.getNameuser());
        fillThePatientRequestTable();
        
        
  
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestTablePatient = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnDeleteReqHosp = new javax.swing.JButton();
        btnApproveReqHospital = new javax.swing.JButton();
        btnRejectReqHospital = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblMedicName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Victim Request");

        jLabel4.setBackground(new java.awt.Color(102, 217, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Victim Request");

        tblRequestTablePatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRequestTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Victim Name", "Age", "Gender", "Purpose of Visit", "Date of requirement", "Date of resolution", "Doctor Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequestTablePatient.setGridColor(new java.awt.Color(0, 0, 0));
        tblRequestTablePatient.setShowGrid(true);
        jScrollPane1.setViewportView(tblRequestTablePatient);

        btnAssignToMe.setBackground(new java.awt.Color(102, 217, 255));
        btnAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAssignToMe.setText("Assign to me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnDeleteReqHosp.setBackground(new java.awt.Color(255, 153, 153));
        btnDeleteReqHosp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDeleteReqHosp.setText("Delete");
        btnDeleteReqHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReqHospActionPerformed(evt);
            }
        });

        btnApproveReqHospital.setBackground(new java.awt.Color(102, 217, 255));
        btnApproveReqHospital.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnApproveReqHospital.setText("Approve");
        btnApproveReqHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveReqHospitalActionPerformed(evt);
            }
        });

        btnRejectReqHospital.setBackground(new java.awt.Color(255, 153, 153));
        btnRejectReqHospital.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRejectReqHospital.setText("Reject");
        btnRejectReqHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectReqHospitalActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 217, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Welcome ");

        lblMedicName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(773, 773, 773))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssignToMe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteReqHosp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApproveReqHospital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRejectReqHospital))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(93, 93, 93)))
                .addComponent(lblMedicName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnApproveReqHospital, btnAssignToMe, btnDeleteReqHosp, btnRejectReqHospital});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRejectReqHospital)
                            .addComponent(btnApproveReqHospital)
                            .addComponent(btnDeleteReqHosp)
                            .addComponent(btnAssignToMe))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnApproveReqHospital, btnAssignToMe, btnDeleteReqHosp, btnRejectReqHospital});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblRequestTablePatient.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to assign the Request", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
           
            
            PatientMedicRequest c =  (PatientMedicRequest)tblRequestTablePatient.getValueAt(selectedRow, 7);
            
            if (c.getMedicName() == null){
                
                if (doctorAvailCheck()){
            c.setMedicName(userAccount.getNameuser());
            //c.setAdd(true);
            c.setStatus("Pending");
            c.setReceiver(userAccount);

            fillThePatientRequestTable();
                }
            else
                {
                    JOptionPane.showMessageDialog(null, "Please completed before assigned task", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            
            

            }
            else
            {
                JOptionPane.showMessageDialog(null, "Patient is already assigned to a Medic", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnDeleteReqHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReqHospActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblRequestTablePatient.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the request", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            PatientMedicRequest c =  (PatientMedicRequest)tblRequestTablePatient.getValueAt(selectedRow, 7);
            
            if (userAccount.getNameuser().equals(c.getMedicName())){

            WorkRequest p=(WorkRequest) tblRequestTablePatient.getValueAt(selectedRow, 7);

            userAccount.getWorkQueue().getWorkRequestList().remove(p);
            ecoSystem.getWorkQueue().getWorkRequestList().remove(p);
            enterprise.getWorkQueue().getWorkRequestList().remove(p);

            JOptionPane.showMessageDialog(null, "You have successfully deleted the request");
            fillThePatientRequestTable();
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "You cannot delete this request", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteReqHospActionPerformed

    private void btnApproveReqHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveReqHospitalActionPerformed
        // TODO add your handling code here:

        int selectedRow= tblRequestTablePatient.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to assign the account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            PatientMedicRequest p=(PatientMedicRequest) tblRequestTablePatient.getValueAt(selectedRow, 7);
            
            

            if(p.getReceiver()!= null){
                if (p.getStatus().equalsIgnoreCase("Pending")) {
                    
                    if (userAccount.getNameuser().equals(p.getMedicName()))
                    {
                    UserDetails a =p.getSender();
                    p.setStatus("Approved");
                    Date resolveDate = new Date();
                    p.setResolveDate(resolveDate);
                    //p.setAdd(false);
                    JOptionPane.showMessageDialog(null, "You have successfully completed the request");
                    fillThePatientRequestTable();
                     validation.sendTextMessage(p.getEmailAdd(), "Regarding Medic Appointment Schedule", "Hi" + " " + p.getPatientName()+","
        + "\n" + "Your appointment has been scheduled with" + " " + p.getMedicName() + " \n"
                             + ". Please wait for further communication.");
       
                    
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "You are not the assigned doctor to approve this request");
                    }
                    
           } else if(p.getStatus().equalsIgnoreCase("Rejected")){
                    JOptionPane.showMessageDialog(null, "Cannot approve the rejected request.");

                }else {
                    JOptionPane.showMessageDialog(null, "Cannot Approve the request 2 times.");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please assign first");
            }

        }
    }//GEN-LAST:event_btnApproveReqHospitalActionPerformed

    private void btnRejectReqHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectReqHospitalActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblRequestTablePatient.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to reject the Request", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            PatientMedicRequest p=(PatientMedicRequest) tblRequestTablePatient.getValueAt(selectedRow, 7);
            if (userAccount.getNameuser().equals(p.getMedicName())){
            if(p.getStatus().equalsIgnoreCase("Approved")){
                JOptionPane.showMessageDialog(null, "Cannot Reject the Approved request", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(p.getStatus().equalsIgnoreCase("Rejected")){
                JOptionPane.showMessageDialog(null, "Cannot Reject the request 2 times", "Warning", JOptionPane.WARNING_MESSAGE);
            }else{
                if (p.getStatus().equalsIgnoreCase("Pending")) {
                    p.setStatus("Rejected");
                    p.setReceiver(userAccount);
                    Date resolveDate = new Date();
                    p.setResolveDate(resolveDate);
                    //p.setAdd(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Please assign first");
                }
            }
            fillThePatientRequestTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Assigned Medic can reject the request", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnRejectReqHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveReqHospital;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnDeleteReqHosp;
    private javax.swing.JButton btnRejectReqHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicName;
    private javax.swing.JTable tblRequestTablePatient;
    // End of variables declaration//GEN-END:variables

    private void fillThePatientRequestTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblRequestTablePatient.getModel();
        
        model.setRowCount(0);
        

        for (WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
           if(work instanceof PatientMedicRequest){ 
            Object[] row = new Object[8];
            row[0] = ((PatientMedicRequest) work).getPatientName();
            row[1] = ((PatientMedicRequest) work).getPatientAge();
            row[2] = ((PatientMedicRequest) work).getPatientGender();
            row[3] = ((PatientMedicRequest) work).getPurposeOfVisit();
            row[4] = ((PatientMedicRequest) work).getRequestDate();
            row[5] = ((PatientMedicRequest) work).getResolveDate();
            row[6] = ((PatientMedicRequest) work).getMedicName();
            row[7] = work;
  
            model.addRow(row);
           }
        }
        
        
    }
    
    
    public boolean doctorAvailCheck(){
           for (WorkRequest work : ecoSystem.getWorkQueue().getWorkRequestList()){
           if(work instanceof PatientMedicRequest){ 
//               System.out.println("Check Error"+((PatientMedicRequest) work).getMedicName());
//               System.out.println("Check Error"+work.getStatus());
                
                if (((PatientMedicRequest) work).getMedicName() == null)
                {
                    return true;
                }
                

               if (((PatientMedicRequest) work).getMedicName().equals(userAccount.getNameuser()) && work.getStatus().equals("Pending"))
               {
                   return false;
                   
               }
               
               
              
               
               
           }
        }
              return true;
    
    }
}
