/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Emergency.PoliceDepartment;

import Model.BloodSupply.BloodSupply;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.OrganizationDirectory;
import Model.PoliceDepartment.PoliceDepartment;
import Model.PoliceDepartment.PoliceDepartmentDirectory;
import Model.UserDetails.UserDetails;
import Model.Utils.HeaderColors;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManagePoliceDepartmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePoliceDepartmentJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserDetails userAccount;
    private EcoSystem ecoSystem;
    public ManagePoliceDepartmentJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory,Enterprise enterprise,UserDetails userAccount,EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
       tblPolice.getTableHeader().setDefaultRenderer(new HeaderColors());
         populatePoliceTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMedic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDeleteMedic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolice = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUnitSize = new javax.swing.JTextField();
        unitTypeComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 153));

        btnAddMedic.setBackground(new java.awt.Color(0, 153, 51));
        btnAddMedic.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAddMedic.setText("Add");
        btnAddMedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administratorBig.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Police Department");

        btnBack.setBackground(new java.awt.Color(102, 217, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteMedic.setBackground(new java.awt.Color(255, 153, 153));
        btnDeleteMedic.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDeleteMedic.setText("Remove");
        btnDeleteMedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedicActionPerformed(evt);
            }
        });

        tblPolice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group Name", "Group Strength"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPolice);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Group Type :");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Group Size :");

        txtUnitSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUnitSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitSizeActionPerformed(evt);
            }
        });

        unitTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Service", "Surveillance Team", "Emergency Respose", "CIA", "Federal Team" }));
        unitTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeleteMedic)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUnitSize)
                                                .addComponent(unitTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnAddMedic))
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel3))))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteMedic)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(unitTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUnitSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddMedic))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicActionPerformed
        // TODO add your handling code here:
       // PoliceDepartmentDirectory policeStationDirectory = new PoliceDepartmentDirectory();
       
        try{
            if(Integer.parseInt(txtUnitSize.getText()) <= 0 ){
        JOptionPane.showMessageDialog(null, "Enter Proper value", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
            
        } catch( NumberFormatException n){
        JOptionPane.showMessageDialog(null, "Enter Proper numeric value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
       
        int flag = 0;
        if(!unitTypeComboBox.getSelectedItem().toString().equals("")){
            System.out.println("check a");
            
            if(ecoSystem.getPoliceDepartmentList().getPoliceDepartmentList().size() == 0){
                System.out.println("check b");
             PoliceDepartment policeStation = ecoSystem.getPoliceDepartmentList().addPolice() ;
            policeStation.setPoliceType(unitTypeComboBox.getSelectedItem().toString());
            policeStation.setUnitCount(Integer.parseInt(txtUnitSize.getText())); 
            flag = 1;
            populatePoliceTable();
            
            } else{
                System.out.println("check c");
                for(PoliceDepartment police : ecoSystem.getPoliceDepartmentList().getPoliceDepartmentList()){
                    System.out.println("check d");
                if(police.getPoliceType().equals(unitTypeComboBox.getSelectedItem().toString())){
                    System.out.println("check e");
                    police.setUnitCount(police.getUnitCount() + Integer.parseInt(txtUnitSize.getText()));
                    flag = 1;
                    populatePoliceTable();
                   return;
                }
                
                }
                
                 if(flag == 0){
                System.out.println("check f");
                 PoliceDepartment policeStation = ecoSystem.getPoliceDepartmentList().addPolice() ;
            policeStation.setPoliceType(unitTypeComboBox.getSelectedItem().toString());
            policeStation.setUnitCount(Integer.parseInt(txtUnitSize.getText())); 
             populatePoliceTable();
            
            }
            
            }
            
           
            
            
//            PoliceDepartment policeStation = ecoSystem.getPoliceDepartmentList().addPolice() ;
//            policeStation.setPoliceType(unitTypeComboBox.getSelectedItem().toString());
//            policeStation.setUnitCount(Integer.parseInt(txtUnitSize.getText())); ;
//
       populatePoliceTable();

//            LocalityBloodRequest communityBloodRequest = new LocalityBloodRequest();
//            communityBloodRequest.setBloodType(bloodBank);
//
//            LocalityDonationRequest communityDonationRequest = new LocalityDonationRequest();
//            communityDonationRequest.setBloodType(bloodBank);
//
//            txtUnitType.setText("");
            //bloodDonationAdd();

        }else{
            JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMedicActionPerformed

    
    private void populatePoliceTable() {
     DefaultTableModel table= (DefaultTableModel) tblPolice.getModel();
     table.setRowCount(0);
      for (PoliceDepartment policeStation : ecoSystem.getPoliceDepartmentList().getPoliceDepartmentList() ) {
            
           Object[] row = new Object[2];
           row[0]= policeStation;
           row[1]=policeStation.getUnitCount() ;
           table.addRow(row);
    }  
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedicActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblPolice.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the police details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            PoliceDepartment p=(PoliceDepartment) tblPolice.getValueAt(selectedRow, 0);

            ecoSystem.getPoliceDepartmentList().removePolice(p); ;
            JOptionPane.showMessageDialog(null, "You have successfully deleted the police details");
            populatePoliceTable();
        }
    }//GEN-LAST:event_btnDeleteMedicActionPerformed

    private void txtUnitSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitSizeActionPerformed

    private void unitTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedic;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteMedic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPolice;
    private javax.swing.JTextField txtUnitSize;
    private javax.swing.JComboBox<String> unitTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
